---
# APIs in this list are accessible by the main endpoints v1/query and v1/asyncquery
include:
  # external (not Su / Wu Lab), non-TRAPI APIs
  # annotated with SmartAPI x-bte
  # also accessible by v1/team/Service Provider/ endpoints and by api-specific endpoints
  - id: d22b657426375a5295e7da8a303b9893
    name: Monarch API
  - id: 0212611d1c670f9107baf00b77f0889a
    name: CTD API
    primarySource: true
  - id: 326eb1e437303bee27d3cef29227125d
    name: Complex Portal Web Service
    primarySource: true
  - id: 43af91b3d7cae43591083bff9d75c6dd
    name: EBI Proteins API
  - id: dca415f2d792976af9d642b7e73f7a41
    name: LitVar API
  - id: 1f277e1563fcfd124bfae2cc3c4bcdec
    name: QuickGO API
  - id: 1c056ffc7ed0dd1229e71c4752239465
    name: Ontology Lookup Service API
  # internal (Su / Wu Lab), non-TRAPI: "pending" BioThings APIs
  # annotated with SmartAPI x-bte
  # also accessible by v1/team/Service Provider/ endpoints and by api-specific endpoints
  - id: 68f12100e74342ae0dd5013d5f453194
    name: BioThings AGR API
  - id: 38e9e5169a72aee3659c9ddba956790d
    name: BioThings BindingDB API
  - id: 55a223c6c6e0291dbd05f2faf27d16f4
    name: BioThings BioPlanet Pathway-Disease API
  - id: b99c6dd64abcefe87dcd0a51c249ee6d
    name: BioThings BioPlanet Pathway-Gene API
  - id: 00fb85fc776279163199e6c50f6ddfc6
    name: BioThings DDInter API
  - id: e3edd325c76f2992a111b43a907a4870
    name: BioThings DGIdb API
  - id: a7f784626a426d054885a5f33f17d3f8
    name: BioThings DISEASES API
  - id: 1f47552dabd67351d4c625adb0a10d00
    name: BioThings EBIgene2phenotype API
  - id: f1b8f64c316a01d1722f0fb842499fe5
    name: BioThings FooDB API
  - id: 895ec14a3650ec7ad85959a2d1554e2f
    name: BioThings FoodData Central API
  - id: cc857d5b7c8b7609b5bbb38ff990bfff
    name: BioThings GO Biological Process API
  - id: f339b28426e7bf72028f60feefcd7465
    name: BioThings GO Cellular Component API
  - id: 34bad236d77bea0a0ee6c6cba5be54a6
    name: BioThings GO Molecular Function API
  - id: 316eab811fd9ef1097df98bcaa9f7361
    name: BioThings GTRx API
  - id: a5b0ec6bfde5008984d4b6cde402d61f
    name: BioThings HPO API
  - id: 32f36164fabed5d3abe6c2fd899c9418
    name: BioThings IDISK API
  - id: e9eb40ff7ad712e4e6f4f04b964b5966
    name: BioThings InnateDB API
  - id: 77ed27f111262d0289ed4f4071faa619
    name: BioThings MGIgene2phenotype API
  - id: edeb26858bd27d0322af93e7a9e08761
    name: BioThings PFOCR API
  - id: b772ebfbfa536bba37764d7fddb11d6f
    name: BioThings RARe-SOURCE API
  - id: 1138c3297e8e403b6ac10cff5609b319
    name: BioThings repoDB API
  - id: 03283cc2b21c077be6794e1704b1d230
    name: BioThings Rhea API
  - id: 1d288b3a3caf75d541ffaae3aab386c8
    name: BioThings SEMMEDDB API
  - id: b48c34df08d16311e3bca06b135b828d
    name: BioThings SuppKG API
  - id: e481efd21f8e8c1deac05662439c2294
    name: Biothings Therapeutic Target Database API
  - id: ec6d76016ef40f284359d17fbf78df20
    name: BioThings UBERON API
  # internal (Su / Wu Lab), non-TRAPI: Core BioThings APIs
  # annotated with SmartAPI x-bte
  # also accessible by v1/team/Service Provider/ endpoints and by api-specific endpoints
  - id: 8f08d1446e0bb9c2b323713ce83e2bd3
    name: MyChem.info API
  - id: 671b45c0301c8624abbd26ae78449ca2
    name: MyDisease.info API
  - id: 59dce17363dce279d389100834e43648
    name: MyGene.info API
  - id: 09c8782d9f4027712e65b95424adba79
    name: MyVariant.info API
  # non-TRAPI: pending BioThings APIs made in collab with Multiomics Provider
  # annotated with SmartAPI x-bte
  # also accessible by v1/team/Service Provider/ and v1/team/Multiomics Provider endpoints, and by api-specific endpoints
  - id: adf20dd6ff23dfe18e8e012bde686e31
    name: Multiomics BigGIM-DrugResponse KP API
  - id: d86a24f6027ffe778f84ba10a7a1861a
    name: Multiomics EHR Risk KP API
  - id: 02af7d098ab304e80d6f4806c3527027
    name: Multiomics Wellness KP API
  # non-TRAPI: pending BioThings APIs made in collab with Text Mining Provider
  # annotated with SmartAPI x-bte
  # also accessible by v1/team/Service Provider/ and v1/team/Text Mining Provider endpoints, and by api-specific endpoints
  - id: 978fe380a147a8641caf72320862697b
    name: Text Mining Targeted Association API
  # TRAPI (Translator standard) APIs: Automat
  # not accessible by team or api-specific endpoints
  # using robokop to access all automat resources at once
  - id: 4f9c8853b721ef1f14ecee6d92fc19b5
    name: Automat-robokop(Trapi v1.5.0)
  # TRAPI (Translator standard) APIs: COHD
  # not accessible by team or api-specific endpoints
  # notes on COHD:
  # - DON'T INGEST 'Columbia Open Health Data (COHD)'/70117385218edc9bc01633829011dfcf
  #   IT IS NOT TRAPI (and may be outdated?)
  # - COHD for COVID-19 should work but BTE gets a 500 when retrieving meta_knowledge_graph...
  #   smartapi ID fc8245e92c970298449294fc04211869
  - id: d4290b6b5741e6da6cc6a6f42e0cfdb5
    name: COHD TRAPI
  # TRAPI (Translator standard) APIs: CHP
  # not accessible by team or api-specific endpoints
  - id: 412af63e15b73e5a30778aac84ce313f
    name: Connections Hypothesis Provider API
  # TRAPI (Translator standard) APIs: Molecular Data Provider
  # not accessible by team or api-specific endpoints
  - id: 1901bab8d33bb70b124f400ec1cfdba3
    name: MolePro
  # # TRAPI (Translator standard) APIs: Multiomics (made with RTX team Plover)
  # # not accessible by team or api-specific endpoints
  # - id: e51073371d7049b9643e1edbdd61bcbd
  #   name: Clinical Trials KP - TRAPI 1.5.0
  - id: edc04feaf16c12424737988ce2e90d60
    name: Drug Approvals KP - TRAPI 1.5.0
  - id: a8be4ea3fe8fa80a952ead0b3c5e4bc1
    name: Microbiome KP - TRAPI 1.5.0
  - id: 1b6de23ed3c4e0713b20794477ba1e39
    name: Multiomics KP - TRAPI 1.5.0
exclude: [] # if adding exclude remove these square brackets
