on: ["push", "pull_request"]

name: Test in workspace

jobs:

  test-coverage:
    name: Generate coverage report
    runs-on: ubuntu-latest
    steps:

    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Checkout to specific branch
      uses: actions/checkout@v3
      id: specific-checkout
      continue-on-error: true
      with:
        repository: biothings/biothings_explorer
        ref: ${{ steps.branch-name.outputs.current_branch }}

    - name: Checkout to main if above failed
      if: steps.specific-checkout.outcome == 'failure'
      uses: actions/checkout@v3
      with:
        repository: biothings/biothings_explorer
        ref: main

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: network logger
      run: |
        sudo -i
        mkdir $HOME/tmp_logs
        sudo tcpdump -n dst host biothings.ci.transltr.io -w $HOME/tmp_logs/http.pcap &

    - name: pnpm install, generate coverage report
      continue-on-error: true
      run: |
        pnpm run clone
        pnpm run git checkout ${{ steps.branch-name.outputs.current_branch }}
        pnpm i
        pnpm --filter bte-server test-cov

    - name: show network logs
      run: |
        sudo killall tcpdump
        sudo tcpdump -A -r $HOME/tmp_logs/http.pcap
      
    - name: Send coverage report to codecov for visualization
      uses: codecov/codecov-action@v3
      with:
        # working-directory: ./packages/@biothings-explorer/bte-trapi
        files: ./coverage/lcov.info
        verbose: true
